# Generated by Django 5.0.1 on 2024-01-21 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('gold', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CountrySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('king', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('construction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.constructiontype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.country')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('level', models.IntegerField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='play.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.countryschema'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.country')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='constructiontype',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.materialtype'),
        ),
        migrations.CreateModel(
            name='TradeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.country')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.tradinghub')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.materialtype')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.tradinghub')),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_lost', to='play.country')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_won', to='play.country')),
            ],
        ),
    ]
